<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api, readSse } from '../api/client'
import ConversationHistoryDrawer, { type HistoryItem } from '../components/ConversationHistoryDrawer.vue'

type Mode = 'discover' | 'validate' | 'compare'
type Score = Record<'demand'|'competition'|'profitability'|'trend'|'differentiation'|'supply'|'risk'|'overall', number>
interface Candidate { candidate_id:string; asin:string; title:string; category:string; price_usd?:number; cost_usd?:number; estimated_margin_pct?:number; review_count?:number; score?:Score }
interface Result { decision?:string; executive_summary:string[]; candidates:Candidate[]; evidence:Array<{evidence_id:string;provider:string;tool:string;claim:string}>; gaps:string[] }
interface Run { run_id:string; title:string; source_text:string; mode:Mode; marketplace:string; status:string; result?:Result; error:string }

const mode=ref<Mode>('discover'), prompt=ref(''), candidateRefs=ref(''), marketplace=ref('US')
const constraints=ref({price_min_usd:18,price_max_usd:60,min_margin_pct:20,target_margin_pct:25,min_roi_pct:50,max_reviews:500,budget_usd:undefined as number|undefined})
const showConstraints=ref(false), run=ref<Run>(), runs=ref<Array<{run_id:string;title:string;status:string;updated_at:string}>>([]), processing=ref(false), progress=ref(''), progressStep=ref(0), error=ref(''), historyOpen=ref(true), replyText=ref('')
const result=computed(()=>run.value?.result)
const historyItems=computed<HistoryItem[]>(()=>runs.value.map(item=>({id:item.run_id,title:item.title,status:item.status,updatedAt:item.updated_at,deletable:!['queued','running'].includes(item.status)})))
const scoreLabels:Array<[keyof Score,string]>=[['demand','需求'],['competition','竞争'],['profitability','利润'],['trend','趋势'],['differentiation','差异化'],['supply','供应链'],['risk','风险']]
async function loadRuns(){runs.value=await api.service('product-research','runs')}
async function loadRun(id:string){run.value=await api.service<Run>('product-research',`runs/${id}`);mode.value=run.value.mode;prompt.value=run.value.source_text;localStorage.setItem('product-research-run',id);if(['queued','running'].includes(run.value.status))await watch(id)}
async function watch(id:string){processing.value=true;try{const response=await fetch(api.serviceUrl('product-research',`runs/${id}/events`));await readSse(response,(event,data)=>{if(event==='status'||event==='progress'){progress.value=data.content||progress.value;progressStep.value=data.step??progressStep.value}if(event==='result'&&run.value)run.value={...run.value,status:data.status,result:data.result};if(event==='error')error.value=data.message});run.value=await api.service<Run>('product-research',`runs/${id}`);await loadRuns()}catch(cause){error.value=cause instanceof Error?cause.message:String(cause)}finally{processing.value=false}}
async function submit(){if(!prompt.value.trim()||processing.value)return;const refs=candidateRefs.value.split(/[\n,]+/).map(v=>v.trim()).filter(Boolean);if(mode.value==='compare'&&refs.length<2){error.value='对比模式至少填写两个候选';return}error.value='';progress.value='正在启动真实市场研究';run.value=await api.service<Run>('product-research','runs',{method:'POST',body:JSON.stringify({mode:mode.value,prompt:prompt.value.trim(),marketplace:marketplace.value,constraints:constraints.value,candidate_refs:refs})});localStorage.setItem('product-research-run',run.value.run_id);await loadRuns();await watch(run.value.run_id)}
async function reply(){if(!run.value||!replyText.value.trim()||processing.value)return;processing.value=true;const text=replyText.value.trim();replyText.value='';try{run.value=await api.service<Run>('product-research',`runs/${run.value.run_id}/reply`,{method:'POST',body:JSON.stringify({text})});progress.value='已收到成本或约束信息，正在重新计算';await watch(run.value.run_id)}catch(cause){error.value=cause instanceof Error?cause.message:String(cause);processing.value=false}}
function reset(){run.value=undefined;prompt.value='';candidateRefs.value='';progress.value='';error.value='';localStorage.removeItem('product-research-run')}
async function renameRun(id:string,title:string){const changed=await api.service<Run>('product-research',`runs/${id}`,{method:'PATCH',body:JSON.stringify({title})});if(run.value?.run_id===id)run.value=changed;await loadRuns()}
async function deleteRun(id:string){await api.service('product-research',`runs/${id}`,{method:'DELETE'});if(run.value?.run_id===id)reset();await loadRuns()}
function download(kind:'json'|'xlsx'){if(run.value)window.location.href=api.serviceUrl('product-research',`runs/${run.value.run_id}/artifacts/${kind}`)}
const decisionText=(value?:string)=>({GO:'建议进入',CONDITIONAL_GO:'有条件进入',NO_GO:'不建议进入'}[value||'']||'等待结论')
onMounted(async()=>{await loadRuns();const remembered=localStorage.getItem('product-research-run');const target=runs.value.find(v=>v.run_id===remembered)?.run_id||runs.value[0]?.run_id;if(target)await loadRun(target)})
</script>

<template>
<section class="page workspace research-layout" :class="{'history-open':historyOpen}">
 <ConversationHistoryDrawer v-model:open="historyOpen" title="Amazon 选品" :items="historyItems" :selected-id="run?.run_id" :busy="processing" @create="reset" @select="loadRun" @rename="renameRun" @delete="deleteRun"/>
 <main class="chat-shell glass-panel"><header class="workspace-head"><div><p class="eyebrow">EVIDENCE DRIVEN · LIVE MARKET DATA</p><h1>Amazon 选品研究</h1><p>发现机会、验证产品并用统一口径比较候选</p></div><div class="stage-pill">{{mode==='discover'?'蓝海发现':mode==='validate'?'定向验证':'候选对比'}}</div></header>
 <div class="chat research-chat"><div v-if="!run" class="research-intake"><div class="mode-tabs"><button v-for="item in ([['discover','蓝海发现'],['validate','定向验证'],['compare','候选对比']] as const)" :key="item[0]" :class="{active:mode===item[0]}" @click="mode=item[0]">{{item[1]}}</button></div><label><span>研究目标</span><textarea v-model="prompt" placeholder="描述品类、预算、目标售价、竞争和利润要求"/></label><label v-if="mode==='compare'"><span>候选（每行一个，2–5 个）</span><textarea v-model="candidateRefs" placeholder="B0XXXXXXXX&#10;B0YYYYYYYY"/></label><button class="constraint-toggle" @click="showConstraints=!showConstraints">{{showConstraints?'收起':'展开'}}筛选约束</button><div v-if="showConstraints" class="constraint-grid"><label>站点<select v-model="marketplace"><option>US</option></select></label><label>预算 USD<input v-model.number="constraints.budget_usd" type="number"/></label><label>最低售价<input v-model.number="constraints.price_min_usd" type="number"/></label><label>最高售价<input v-model.number="constraints.price_max_usd" type="number"/></label><label>最低利润率<input v-model.number="constraints.min_margin_pct" type="number"/></label><label>目标利润率<input v-model.number="constraints.target_margin_pct" type="number"/></label><label>最低 ROI<input v-model.number="constraints.min_roi_pct" type="number"/></label><label>最大评论数<input v-model.number="constraints.max_reviews" type="number"/></label></div></div>
 <div v-else class="message user"><span class="avatar">你</span><div class="bubble">{{run.source_text}}</div></div><div v-if="processing" class="message assistant"><span class="avatar">AI</span><div class="bubble typing"><i/><i/><i/> {{progress||'Agent 正在处理'}}</div></div>
 <div v-if="result" class="message assistant"><span class="avatar">AI</span><div class="bubble research-report"><header class="decision-head"><div><p class="eyebrow">PRODUCT OPPORTUNITY DECISION</p><h2>{{decisionText(result.decision)}}</h2></div><strong>{{result.decision||'PENDING'}}</strong></header><ul><li v-for="item in result.executive_summary" :key="item">{{item}}</li></ul><h3>候选机会</h3><div class="candidate-table"><table><thead><tr><th>产品</th><th>售价</th><th>成本</th><th>利润率</th><th>评论</th><th>总分</th></tr></thead><tbody><tr v-for="candidate in result.candidates" :key="candidate.candidate_id"><td><b>{{candidate.title}}</b><small>{{candidate.asin||candidate.category}}</small></td><td>{{candidate.price_usd??'—'}}</td><td>{{candidate.cost_usd??'—'}}</td><td>{{candidate.estimated_margin_pct!=null?`${candidate.estimated_margin_pct}%`:'待补充'}}</td><td>{{candidate.review_count??'—'}}</td><td><strong>{{candidate.score?.overall??'—'}}</strong></td></tr></tbody></table></div><details v-if="result.evidence.length"><summary>数据证据（{{result.evidence.length}}）</summary><article v-for="item in result.evidence.slice(0,30)" :key="item.evidence_id" class="evidence"><b>{{item.provider}} · {{item.tool}}</b><span>{{item.claim}}</span></article></details><div v-if="result.gaps.length" class="report-gaps"><b>数据缺口</b><ul><li v-for="gap in result.gaps" :key="gap">{{gap}}</li></ul></div><div class="artifact-actions"><button class="btn ghost" @click="download('json')">下载 JSON</button><button class="btn primary" @click="download('xlsx')">下载 Excel</button></div></div></div><div v-if="error" class="alert">{{error}}</div></div>
 <form v-if="!run" class="composer" @submit.prevent="submit"><small>只使用真实数据源，不用模拟数据补齐结论</small><button class="send" :disabled="processing||!prompt.trim()">开始研究</button></form><form v-else-if="run.status==='needs_clarification'" class="composer" @submit.prevent="reply"><textarea v-model="replyText" placeholder="补充采购成本、重量、尺寸、MOQ 或其他缺失条件"/><button class="send" :disabled="processing||!replyText.trim()">继续</button></form></main>
 <aside class="runtime glass-panel"><p class="eyebrow">LIVE RESEARCH</p><h2>实时研究进度</h2><div class="progress"><span :style="{width:`${Math.min(100,progressStep/8*100)}%`}"/></div><p>{{progress||'等待研究目标'}}</p><div class="steps"><span v-for="step in ['解析目标与约束','检查真实数据源','类目与关键词发现','市场与竞品采集','供应链与成本','确定性评分','证据复核','生成报告']" :key="step">{{step}}</span></div><template v-if="result?.candidates?.[0]?.score"><h3>领先候选评分</h3><div class="mini-scores"><div v-for="entry in scoreLabels" :key="entry[0]"><span>{{entry[1]}}</span><i><b :style="{width:`${result.candidates[0].score?.[entry[0]]||0}%`}"/></i><strong>{{result.candidates[0].score?.[entry[0]]}}</strong></div></div></template><section v-if="result" class="coverage"><h3>证据覆盖</h3><strong>{{result.evidence.length}}</strong> 条已记录证据<p v-if="result.gaps.length" class="danger-text">{{result.gaps.length}} 个数据缺口</p></section></aside>
</section>
</template>

<style scoped>
.research-intake{max-width:900px;margin:auto;padding:12px}.mode-tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:20px}.mode-tabs button,.constraint-toggle{border:1px solid var(--border);background:rgba(255,255,255,.025);color:#7898aa;border-radius:10px;padding:11px;cursor:pointer}.mode-tabs button.active{color:white;border-color:var(--cyan);background:rgba(67,223,252,.09)}.research-intake>label{display:grid;gap:7px;color:#94b4c5;font-size:12px;margin-bottom:13px}.research-intake textarea{min-height:120px;resize:vertical;background:#061522;border:1px solid var(--border);color:white;border-radius:12px;padding:13px}.constraint-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:10px}.constraint-grid label{display:grid;gap:4px;color:#7898aa;font-size:10px}.constraint-grid input,.constraint-grid select{min-width:0;background:#061522;border:1px solid var(--border);color:white;border-radius:7px;padding:8px}.composer small{flex:1;color:#547486;align-self:center}.research-report{width:100%;max-width:100%}.decision-head{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--border)}.decision-head>strong{color:#75e6c1}.candidate-table{overflow:auto}.candidate-table table{width:100%;border-collapse:collapse;font-size:12px}.candidate-table th,.candidate-table td{padding:9px;text-align:left;border-bottom:1px solid var(--border)}.candidate-table td:first-child{min-width:220px}.candidate-table small,.evidence span{display:block;color:#638397}.evidence{padding:8px;border-bottom:1px solid var(--border);font-size:11px}.report-gaps{padding:10px;margin-top:12px;background:rgba(255,190,60,.07);color:#d6b878}.artifact-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.mini-scores{display:grid;gap:8px}.mini-scores>div{display:grid;grid-template-columns:48px 1fr 28px;gap:6px;align-items:center;font-size:10px;color:#7898aa}.mini-scores i{height:4px;background:#071625}.mini-scores i b{display:block;height:100%;background:var(--cyan)}.coverage{border-top:1px solid var(--border);margin-top:22px;padding-top:14px}.coverage>strong{font:300 30px monospace;color:var(--cyan)}@media(max-width:900px){.constraint-grid{grid-template-columns:repeat(2,1fr)}}
.mode-tabs button,
.constraint-toggle { border-color: var(--border); background: hsl(0 0% 100% / .025); color: var(--muted); border-radius: 999px; transition: transform .2s, background .2s; }
.mode-tabs button.active { color: white; border-color: hsl(0 0% 100% / .35); background: hsl(0 0% 100% / .09); }
.research-intake > label { color: hsl(0 0% 100% / .65); }
.research-intake textarea,
.constraint-grid input,
.constraint-grid select { background: hsl(0 0% 0% / .26); border-color: var(--border); color: white; border-radius: 14px; }
.constraint-grid label,
.composer small,
.candidate-table small,
.evidence span,
.mini-scores > div { color: var(--muted); }
.decision-head { border-color: var(--border); }
.decision-head > strong { color: hsl(0 0% 100% / .76); }
.report-gaps { background: hsl(0 0% 100% / .055); color: hsl(0 0% 100% / .68); border-radius: 14px; box-shadow: inset 3px 0 0 hsl(0 0% 100% / .35); }
.mini-scores i { background: hsl(0 0% 100% / .08); }
.mini-scores i b { background: hsl(0 0% 100% / .82); }
.coverage { border-color: var(--border); }
.coverage > strong { color: white; }
</style>
