import { FormEvent, useState } from "react";
import { sendTurn } from "./api";
import type { CreationSession } from "./types";

const stages = ["brief", "audience", "product", "competitor", "selling_points", "keywords", "final_copy", "image_handoff"];
const labels: Record<string, string> = { brief: "Brief 与事实台账", audience: "受众与市场", product: "产品解读", competitor: "竞品分析", selling_points: "五大卖点", keywords: "关键词意图", final_copy: "最终文案", image_handoff: "图片交接", completed: "完成" };

export default function App() {
  const [session, setSession] = useState<CreationSession | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { setSession(await sendTurn(message, session)); setMessage(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "请求失败"); } finally { setBusy(false); } }
  async function action(text: string) { setBusy(true); try { setSession(await sendTurn(text, session)); } catch (reason) { setError(reason instanceof Error ? reason.message : "请求失败"); } finally { setBusy(false); } }
  const deliverable = session?.deliverable;
  return <main><header><div><p className="eyebrow">AMAZON LISTING CREATION · REACT</p><h1>Listing 创作 Agent</h1><p>审批门与证据控制驱动的完整创作流程</p></div><button onClick={() => setSession(null)}>新建会话</button></header><div className="layout"><aside><h2>创作进度</h2>{stages.map((stage, index) => { const current = session?.stage ?? "brief"; const mark = stages.indexOf(current) > index || current === "completed" ? "✓" : current === stage ? "▶" : "○"; return <p className={current === stage ? "current" : ""} key={stage}>{mark} {labels[stage]}</p>; })}<hr/><p>状态：<b>{session?.status ?? "等待 Brief"}</b></p><p>版本：{session?.revision ?? 0}</p></aside><section className="workbench"><div className="message">{session?.last_message_zh || "请提供产品名称、目标站点和规格参数"}</div>{session?.artifacts[session.stage] && <details open><summary>阶段产物</summary><pre>{JSON.stringify(session.artifacts[session.stage].payload, null, 2)}</pre></details>}{deliverable && <div className="deliverable"><h2>可复制成稿 · {deliverable.policy_status}</h2><label>Title<textarea readOnly value={deliverable.title}/></label><label>Item Highlights<textarea readOnly value={deliverable.item_highlights}/></label>{deliverable.bullets.map((bullet, index) => <label key={index}>Bullet {index + 1}<textarea readOnly value={bullet.text}/></label>)}<label>Search Terms<textarea readOnly value={deliverable.search_terms}/></label></div>}<form onSubmit={submit}><textarea value={message} onChange={event => setMessage(event.target.value)} placeholder="产品: …&#10;站点: US&#10;规格: …" required/><div className="actions"><button type="button" onClick={() => action("认可")} disabled={!session || busy}>认可当前阶段</button>{session?.stage === "competitor" && <button type="button" onClick={() => action("跳过竞品")}>跳过竞品</button>}<button className="primary" disabled={busy}>{busy ? "处理中…" : "发送"}</button></div>{error && <p className="error">{error}</p>}</form></section></div></main>;
}
